name: Deploy Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    env:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

    steps:
      - name: Notify Discord: Deployment Started
        run: |
          $body = @{
            content = ":rocket: Deployment started on branch $env:GITHUB_REF_NAME by $env:GITHUB_ACTOR."
          } | ConvertTo-Json
          Invoke-RestMethod -Uri $env:DISCORD_WEBHOOK_URL -Method POST -Body $body -ContentType 'application/json'
        shell: powershell

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.33'

      - name: Publish bot
        run: dotnet publish -c Release -o publish

      - name: Stop bot service
        run: nssm stop TheFirmDiscordBot
        shell: powershell

      - name: Copy files to deployment folder
        run: Copy-Item -Path ./publish/* -Destination "C:\\FirmDiscordBot\\publish" -Recurse -Force
        shell: powershell

      - name: Start bot service
        run: nssm start TheFirmDiscordBot
        shell: powershell

      - name: Notify Discord: Deployment Succeeded
        if: success()
        run: |
          $body = @{
            content = ":white_check_mark: Deployment succeeded on branch $env:GITHUB_REF_NAME by $env:GITHUB_ACTOR."
          } | ConvertTo-Json
          Invoke-RestMethod -Uri $env:DISCORD_WEBHOOK_URL -Method POST -Body $body -ContentType 'application/json'
        shell: powershell

      - name: Notify Discord: Deployment Failed
        if: failure()
        run: |
          $body = @{
            content = ":x: Oh dear, Deployment failed on branch $env:GITHUB_REF_NAME by $env:GITHUB_ACTOR."
          } | ConvertTo-Json
          Invoke-RestMethod -Uri $env:DISCORD_WEBHOOK_URL -Method POST -Body $body -ContentType 'application/json'
        shell: powershell
